'use strict';

const actions = {
	SET_TAB: 'SET_TAB',
	DELETE_TAB: 'DELETE_TAB',
	ACTIVATE_TAB: 'ACTIVATE_TAB',
	DOMAIN_SETTINGS: 'DOMAIN_SETTINGS',
	GLOBAL_SETTINGS: 'GLOBAL_SETTINGS',
	UPDATE_STATE: 'UPDATE_STATE',
	LOAD_ACTIVE_TAB: 'LOAD_ACTIVE_TAB'
};

export default actions;